# Generated by Django 4.0 on 2022-01-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celulares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('sistema_operativo', models.CharField(max_length=50)),
                ('memoria_en_GB', models.PositiveBigIntegerField()),
                ('compañia', models.CharField(max_length=50)),
                ('cantidad', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
